language: node_js

node_js:
- '8'
- '9'
- '10'

# Use container-based Travis infrastructure.
sudo: false

branches:
  only:
  - master
  - "/^greenkeeper/.*$/"

env:
  global:
  - secure: dzmNjqUolYVjlRLVhYWZsR/GLvlGiZhtrAnopY4iGgCmXS+HhutTxdgMpY4bu+jMcr7/ptMKh5l/DlNUjvYOC5R+j9QP1Fx/f8nAXH7e7jPQ+dkFBnVhVffR9SOSb6iWBLLKki1358pe6wCfxOSpJm/C7XvF/2jj+mxGPJVr9jrQSCOCg3taXkJTQRX+xYf3KE3ZajmlDMc3wX7Is/mfS4Euoke77euXm5MOgESxecyiadudlqEEt0o80kPB639hIr86zkmwmc4T2cnErhz0o/TARxGj8awn+x3vdrGX2hB5N6ZWADKhc6iLqaptK+dQgwraUkBWsdnTiB5XMS5eRPlHrie0ATdboR+6iH7cyaVlcSe2Zdk2V5SlciehY7moSSU9bnK3NauPCTnX0+NkUC48/DMNYUW1R6uTMqD8qXqKqyhHAFVCU1FaoSlOJRS5MwHZXNQLXPZRdCzod9e72EkdF+6M3lBHwzuVs2kz1+3DbZ2Vlwbe/amfYZ1wfZjiPF791g4U5xy8no1ZA25EGMuJsI1eiAevLtShdqxPNvazclj94/8PdomSSchC1DpNoyobFxGH6QTGCc8yKVgyXJyX1z77uFvRcYoviFfNuup96B1lP/wg/h55NaSHQMaulWwcuwiRkeJXziuTO1wL48invbInsFmStYzwvbyp+LU=

script:
- yarn test

after_success:
- $(yarn bin)/nyc report --reporter=text-lcov | $(yarn bin)/coveralls
- bash <(curl -s https://codecov.io/bash)
